### ISSUE TITLE
Immediate ballot unlock

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#179]
When scoring the first project, I see the "Nice work! You're ready to unlock your ballot and allocate rewards" banner. Following this, I'm unable to score project

To repro
1. Create new address
2. Connect to app and start to review projects
3. See banner and click "unlock ballot"
4. Go back to score project and see that you can't

<img width="1512" alt="Screenshot 2024-09-23 at 18 00 25" src="https://github.com/user-attachments/assets/0788ebc8-5273-416c-8f65-ca804c53cf05">

<img width="1512" alt="Screenshot 2024-09-23 at 18 01 45" src="https://github.com/user-attachments/assets/2b5562b1-60fb-4efc-aa82-e7d45f6eab2d">

**Comment by nitegeist** [comment]
@JSeiferth I've pushed a fix for this so feel free to test it again. I'm keeping it open just in case it reappears.

**Comment by JSeiferth** [comment]
@nitegeist still encountering the same issue. Tested with a fresh address

**Comment by JSeiferth** [comment]
Just a ping that I'm experiencing this issue again. Always when setting up a new wallet. Weirdly enough, after "unlocking ballot" I can then rate projects, see video below
<img width="1512" alt="Screenshot 2024-09-25 at 19 05 24" src="https://github.com/user-attachments/assets/45c7cbce-c8e8-4216-aeda-333566019e74">

https://github.com/user-attachments/assets/87c881ca-089a-4722-81ad-d27969b492cd
